"""Publish the additive engineer file protocol without rewriting the legacy freeze."""

import argparse
import hashlib
import json
from pathlib import Path

from pydantic import JsonValue

from .core import ProtocolError, digest
from .engineer_examples import engineer_examples


def json_bytes(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode()


def typescript(schema: dict[str, JsonValue]) -> str:
    """Render the JSON-schema constructs emitted by these Pydantic wire models."""
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return "(" + " | ".join(typescript(value) for value in schema["anyOf"]) + ")"
    kind = schema.get("type")
    if kind == "array":
        return "ReadonlyArray<" + typescript(schema["items"]) + ">"
    if kind == "object":
        if "properties" in schema:
            required = schema.get("required", [])
            fields = [
                "  "
                + json.dumps(name)
                + ("" if name in required else "?")
                + ": "
                + typescript(value)
                + ";"
                for name, value in sorted(schema["properties"].items())
            ]
            return "{\n" + "\n".join(fields) + "\n}"
        extra = schema.get("additionalProperties", {})
        return (
            "Record<string, " + (typescript(extra) if isinstance(extra, dict) else "unknown") + ">"
        )
    if kind in {"string", "boolean", "null"}:
        return str(kind)
    if kind in {"integer", "number"}:
        return "number"
    if not schema:
        return "unknown"
    raise ValueError("unsupported TypeScript schema construct: " + str(schema))


def export_engineer_protocol(output: Path) -> dict[str, JsonValue]:
    examples = engineer_examples()
    files: dict[str, bytes] = {}
    components: dict[str, JsonValue] = {}
    for name, example in sorted(examples.items()):
        model = type(example)
        files[f"schemas/{name}.json"] = json_bytes(model.model_json_schema())
        files[f"examples/{name}.json"] = json_bytes(example.model_dump(mode="json"))
        schema = model.model_json_schema(ref_template="#/components/schemas/{model}")
        for key, value in schema.pop("$defs", {}).items():
            if key in components and components[key] != value:
                raise ValueError("conflicting schema definition: " + key)
            components[key] = value
        components[name] = schema
    api = {
        "openapi": "3.1.0",
        "info": {"title": "Engineer file contracts", "version": "1"},
        "paths": {},
        "components": {"schemas": components},
        "x-file-contracts": {
            "submission": "EngineerSubmissionRecord",
            "claimed_report": "EngineerClaimedReport",
            "trusted_review": "EngineerRegressionReport",
            "public_review": "EngineerPublicReport",
        },
    }
    files["openapi.json"] = json_bytes(api)
    files["types.ts"] = (
        "// Generated by career_lab.contracts.v2.engineer_export; do not edit.\n"
        + "\n".join(
            "export type " + name + " = " + typescript(schema) + ";\n"
            for name, schema in sorted(components.items())
        )
    ).encode()
    manifest = {
        "protocol": "engineer-review-v1",
        "legacy_namespace": "career_lab.contracts.v2.research",
        "python_namespace": "career_lab.contracts.v2.engineer",
        "decoder": "decode_engineer_document",
        "consumers": ["engineer", "integration", "feedback"],
        "source_files": {
            name: hashlib.sha256(Path(__file__).with_name(name).read_bytes()).hexdigest()
            for name in ("engineer.py", "engineer_examples.py", "engineer_export.py")
        },
        "legacy_manifest_sha256": hashlib.sha256(
            (
                Path(__file__).resolve().parents[4] / "docs/contracts/expansion-v3/manifest.json"
            ).read_bytes()
        ).hexdigest(),
        "files": {name: hashlib.sha256(raw).hexdigest() for name, raw in sorted(files.items())},
    }
    manifest["revision"] = "engineer-review-v1-" + digest(manifest)
    files["manifest.json"] = json_bytes(manifest)
    if output.exists():
        existing = {
            p.relative_to(output).as_posix(): p.read_bytes()
            for p in output.rglob("*")
            if p.is_file()
        }
        if existing != files:
            raise ProtocolError("immutable_contract_output_exists", status=409)
        return manifest
    output.mkdir(parents=True)
    for name, raw in files.items():
        target = output / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(raw)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    result = export_engineer_protocol(args.output)
    print(json.dumps({"revision": result["revision"], "output": str(args.output)}))


if __name__ == "__main__":
    main()
