import { T, when, isChinese, locale } from './i18n';
import { icon, assistantMark, agentMark } from './art.js';
import { materialTitle } from './vocab.js';

const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button = (label, action, attrs='', cls='quiet') => `<button type="button" class="btn small ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
export const investigationSourceKey = (sessionId, block) => [sessionId, block.testId, block.material?.id, block.material?.version].join('|');
const blockTitle = b => ({ note: b.title || T('调查思路','Investigation notes'), test_compare:T('测试记录对照','Compare test records'), source_check:T('回答与资料版本','Answer and source versions'), retest:T('下一步验证','Check the next step') })[b.type];
const glyph = type => ({note:'note',test_compare:'flask',source_check:'layers',retest:'refresh'})[type];

export function investigationPreview(work) {
  return `<article class="investigation-preview"><span class="inv-eyebrow">${icon('layers','i-sm')}${T('可组合的调查视图','Composable investigation')}</span><h3>${esc(work.title)}</h3><p>${esc(work.question)}</p><ol>${work.blocks.map((b,i)=>`<li><span class="inv-number">${String(i+1).padStart(2,'0')}</span>${icon(glyph(b.type),'i-sm')}<div><b>${esc(blockTitle(b))}</b><p>${b.type==='note'?esc(b.text):b.type==='test_compare'?T(b.testIds.length+' 次真实测试',b.testIds.length+' actual test runs'):b.type==='source_check'?T('核对实际引用与所选资料版本','Check the actual citation against the selected source version'):esc(b.label || T('由你决定是否重测','You decide whether to rerun'))}</p></div></li>`).join('')}</ol><footer>${T('模块和顺序由 Agent 提出；证据由工作台核对，操作由你发起。','The agent proposes modules and their order. The workspace verifies evidence; you initiate actions.')}</footer></article>`;
}

function runFacts(run) {
  const citations=run.citations || [];
  return `<div class="inv-facts"><span>${T('配置 v','Config v')}${run.configVersion}</span>${citations.map(c=>`<span>${esc(materialTitle({id:c.id,title:c.title}))} · v${c.version}</span>`).join('')}${run.fallback?`<span>${T('兜底回答','Fallback')}</span>`:''}${run.stale?`<span class="warn">${T('当时引用已过期','Citation was stale at the time')}</span>`:''}</div>`;
}
function runPanel(run, label, md, canCite) {
  if (!run) return `<section class="inv-pane"><h4>${esc(label)}</h4><p class="inv-missing">${T('这条真实运行记录暂未取得。','This actual run is not available yet.')}</p></section>`;
  return `<section class="inv-pane"><header><span class="inv-pane-label">${esc(label)}</span>${run.createdAt?`<time>${esc(when(run.createdAt))}</time>`:''}</header><p class="inv-question">${esc(run.question)}</p><div class="prose inv-answer"${isChinese(run.answer)?' lang="zh-CN"':''}>${md(run.answer)}${locale()==='en'&&isChinese(run.answer)?'<small class="msg-local">Chinese source</small>':''}</div>${runFacts(run)}<div class="inv-pane-actions">${button(icon('doc','i-xs')+T('查看引用','View citations'),'run-source',`data-run="${esc(run.id)}"`)}${button(icon('quote','i-xs')+T('引用结果','Cite result'),'investigation-cite',`data-id="${esc(run.id)}" ${canCite?'':'disabled'}`)}</div></section>`;
}
function materialPane(material, label, version, md, waiting) {
  return `<section class="inv-pane"><header><span class="inv-pane-label">${esc(label)}</span><span class="stamp">v${version ?? '—'}</span></header>${material?`<h4>${esc(materialTitle(material))}</h4><div class="prose inv-material"${isChinese(material.content)?' lang="zh-CN"':''}>${md(material.content,{dropTitle:true})}</div>`:`<p class="inv-missing">${icon(waiting?'sync':'info','i-sm')}${waiting?T('正在读取这个版本…','Loading this exact version…'):T('这个版本的正文暂未取得。不会用其他版本替代。','This version is unavailable. Another version is not substituted.')}</p>`}</section>`;
}

export function investigationView({work,attempt,session,mutable,readOnly,canRun,busy,cache,errors,controls,strip,md}) {
  const pending=session?.pending, canCite=mutable&&work.adopted;
  const origin=work.ruleOrigin?T('规则起始视图','Rule-based starting view'):T('外部 Agent 组合','Composed by your agent');
  return `<div class="obj-pad investigation-work"><article class="paper investigation-paper">${strip}${controls}<header class="investigation-head"><div class="inv-kicker"><span class="inv-eyebrow">${icon('layers','i-sm')}${T('调查','Investigation')}</span><span class="inv-origin">${work.ruleOrigin?'':agentMark('xs')}${origin}</span></div><label class="sr-only" for="editor-title">${T('标题','Title')}</label><input id="editor-title" class="editor-title" data-edit="title" value="${esc(work.title)}" maxlength="160" ${mutable?'':'readonly'}><div class="editor-meta"><span data-revision>v${work.revision}</span><span>${T(work.blocks.length+' 个模块',work.blocks.length+' modules')}</span><span data-save></span></div><label class="inv-purpose">${T('要弄清什么','What are we trying to understand?')}<textarea id="investigation-question" data-investigation-question rows="2" maxlength="1000" ${mutable?'':'readonly'}>${esc(work.question)}</textarea></label></header>
    ${readOnly||!work.adopted?`<p class="inv-adoption-note">${icon('eye','i-sm')}${readOnly?T('当前练习只读，可查看已保存证据。','This practice is read-only. Saved evidence is available to review.'):T('先检查并采用；读取证据不会运行测试。','Review and adopt before running tests. Reading evidence does not run them.')}</p>`:''}
    <div class="investigation-blocks">${work.blocks.map((block,index)=>{
      const key=investigationSourceKey(attempt.id,block), state=cache[key], run=attempt.tests.find(r=>r.id===block.testId);
      const waiting=pending?.localRun?.investigationId===work.id&&pending.localRun.blockId===block.id;
      const outcomes=attempt.tests.filter(r=>r.investigationId===work.id&&r.blockId===block.id).slice().reverse();
      let content='';
      if(block.type==='note') content=`<div class="inv-note prose">${md(block.text)}</div><span class="inv-note-origin">${work.ruleOrigin?T('规则整理，供你核对','Rule-based, for your review'):T('Agent 的分析，供你核对','Agent analysis, for your review')}</span>`;
      if(block.type==='test_compare') content=`<div class="inv-grid">${block.testIds.map((id,i)=>runPanel(attempt.tests.find(r=>r.id===id),T('测试 '+(i+1),'Test '+(i+1)),md,canCite)).join('')}</div>`;
      if(block.type==='source_check') {
        const cited=run?.citations.find(c=>c.id===block.material.id);
        const latest=attempt.backend?.materials.find(m=>m.id===block.material.id);
        content=`${run?`<div class="inv-source-answer"><span>${assistantMark('xs')}${T('这次实际回答','Actual answer')}</span><div class="prose inv-source-answer-text"${isChinese(run.answer)?' lang="zh-CN"':''}>${md(run.answer,{dropTitle:true})}</div></div>`:''}<div class="inv-grid">${materialPane(state?.citation?.material,T('回答实际引用','Actually cited'),cited?.version,md,!state||state.loading)}${materialPane(state?.selected,T('这次选择核对','Selected for comparison'),block.material.version,md,!state||state.loading)}</div>${latest&&latest.version!==block.material.version?`<p class="inv-version-note">${icon('stale','i-xs')}${T('当前资料已到 v'+latest.version+'，这里保留你选择的 v'+block.material.version+'。','The current source is v'+latest.version+'. This view keeps your selected v'+block.material.version+'.')}</p>`:''}${state?.error?`<p class="inv-version-note">${esc(state.error)}</p>`:''}${state&&!state.loading&&(!state.citation?.material||!state.selected)?button(T('重新读取','Try loading again'),'investigation-load',`data-id="${esc(block.id)}"`):''}`;
      }
      if(block.type==='retest') content=`<p class="inv-retest-question">${icon('flask','i-sm')}${esc(run?.question || T('原测试暂不可用','Original test unavailable'))}</p><p class="inv-retest-note">${T('沿用问题，使用当前试点设置；不会自动刷新索引。','Same question, current pilot settings. The index is not refreshed automatically.')}</p><div class="inv-action-row">${button(icon('refresh','i-sm')+esc(block.label || T('按当前设置重测','Rerun with current settings')),'investigation-retest',`data-id="${esc(block.id)}" ${canRun&&work.adopted&&run&&!waiting?'':'disabled'}`,'primary')}${button(icon('gear','i-sm')+T('查看设置','View settings'),'config')}${waiting?`<span class="inv-run-state" role="status">${busy?T('正在运行…','Running…'):T('结果待确认','Awaiting confirmation')}</span>`:''}</div>${waiting&&!busy?button(T('恢复原请求','Resume request'),'live-retry','','primary'):''}${errors[block.id]?`<p class="inv-error" role="alert">${esc(errors[block.id])}</p>`:''}${outcomes.length?`<div class="inv-result-label">${T('重测已返回 · 新旧记录均保留','Rerun received · both records kept')}</div><div class="inv-grid">${runPanel(run,T('作为起点的运行','Original run'),md,canCite)}${runPanel(outcomes[0],T('这次重测','Latest rerun'),md,canCite)}</div>`:''}`;
      return `<section class="investigation-block" data-investigation-block="${esc(block.id)}"><header class="inv-block-head"><span class="inv-number">${String(index+1).padStart(2,'0')}</span><h3>${esc(blockTitle(block))}</h3><span class="spacer"></span>${mutable?`<div class="inv-order"><button type="button" class="btn icon quiet small" data-action="investigation-move" data-id="${esc(block.id)}" data-dir="-1" aria-label="${esc(T('模块 '+(index+1)+' 上移','Move module '+(index+1)+' up'))}" title="${esc(T('上移','Move up'))}" ${index===0?'disabled':''}>${icon('back','i-xs')}</button><button type="button" class="btn icon quiet small" data-action="investigation-move" data-id="${esc(block.id)}" data-dir="1" aria-label="${esc(T('模块 '+(index+1)+' 下移','Move module '+(index+1)+' down'))}" title="${esc(T('下移','Move down'))}" ${index===work.blocks.length-1?'disabled':''}>${icon('chev','i-xs')}</button></div>`:''}</header>${content}</section>`;
    }).join('')}</div>
    <footer class="investigation-foot"><span>${T('证据来自真实记录；结论由你核对。','Evidence comes from actual records. You review the conclusions.')}</span>${button(agentMark('xs')+T('交给我的 Agent 重组','Let my agent reorganize'),'agent')}</footer></article></div>`;
}
