"""Reviewed-content candidates for optional follow-up practice; no score or routing authority.

These retain the existing v1 urgent/capacity15 constraint changes in the v2
business world. All derivatives remain in the same training component.
"""

from copy import deepcopy
from career_lab.contracts.v2 import ProtocolError

SCENARIOS = {
    "pm_pilot": {"capacity": 30, "dev_days": 3, "deadline_day": 7},
    "pm_pilot_urgent": {"capacity": 30, "dev_days": 3, "deadline_day": 5},
    "pm_pilot_capacity15": {"capacity": 15, "dev_days": 3, "deadline_day": 7},
}


def resources(scenario_id):
    if scenario_id not in SCENARIOS:
        raise ProtocolError("unknown_practice_scenario")
    return dict(SCENARIOS[scenario_id])


def material_definitions(locale, min_score, scenario_id="pm_pilot"):
    if locale == "en":
        from .content_en import materials

        definitions = deepcopy(materials(min_score))
    else:
        from .content import materials

        definitions = deepcopy(materials())
    limits = resources(scenario_id)
    if scenario_id == "pm_pilot":
        return definitions
    # Change the single authoritative constraint paragraph, keeping source spans
    # and all dependent facts freshly generated by build_seed.
    for index, definition in enumerate(definitions):
        mid, title, domain, version, mode, rows = definition
        if mid != "brief" or version != 1:
            continue
        for row_index, row in enumerate(rows):
            if not isinstance(row, tuple) or not any(f[0] == "capacity" for f in row[1]):
                continue
            if locale == "en":
                sentence = (
                    f"The project currently has capacity for {limits['capacity']} people, "
                    f"{limits['dev_days']} developer-days and a pilot deadline of day {limits['deadline_day']}."
                )
            else:
                sentence = (
                    f"目前为项目预留的容量是{limits['capacity']}人，可用开发资源{limits['dev_days']}人日，"
                    f"正式试点期限为第{limits['deadline_day']}天。"
                )
            rows[row_index] = (
                sentence,
                [(fid, limits.get(fid, value), unit) for fid, value, unit in row[1]],
            )
        if locale == "en":
            rows.append(
                (
                    "The saved setup is a preparation draft for 20 participants on day 7. Saving a setup does not mean its resources or launch date are approved. Use the allocation above when deciding what to propose.",
                    [("draft_participants", 20, "people"), ("draft_launch_day", 7, "days")],
                )
            )
        else:
            rows.append(
                (
                    "当前保存的是20人、第7天的筹备配置草案。已有草案不代表资源或上线日期已获批；本次委托以上方预留为准，请核对后决定提出什么建议。",
                    [("draft_participants", 20, "人"), ("draft_launch_day", 7, "天")],
                )
            )
        definitions[index] = (mid, title, domain, version, mode, rows)
    return definitions


def practice_paths(paths, scenario_id):
    """Private regression candidates, never learner suggestions or gold scores."""
    paths = deepcopy(paths)
    limits = resources(scenario_id)
    if scenario_id == "pm_pilot":
        return paths
    for path in paths:
        if path["id"] != "delayed_realtime":
            path["launch_day"] = limits["deadline_day"]
        if path["id"] in {"stable_narrow", "manual_policy"}:
            path["participants"] = min(path["participants"], limits["capacity"])
        elif path["id"] == "delayed_realtime" and limits["capacity"] < path["participants"]:
            path["request"]["capacity"] = path["participants"]
    return paths
