// Generated by career_lab.contracts.v2.engineer_export; do not edit.
export type AssistantConfig = {
  "chunk_size"?: number;
  "config_version"?: number;
  "domains": ReadonlyArray<string>;
  "fallback"?: "human" | "none";
  "freshness_guard"?: "none" | "warn" | "fallback";
  "id": string;
  "launch_day"?: number;
  "manual_domains"?: ReadonlyArray<string>;
  "min_score"?: number;
  "min_score_calibration"?: (FileRef | null);
  "participants"?: number;
  "prohibited_topics"?: ReadonlyArray<string>;
  "retrieval_limit"?: number;
  "schema_version"?: 2;
  "scope_filter"?: boolean;
  "session_id": string;
  "update_strategy"?: "daily" | "realtime" | "manual_policy";
  "version"?: number;
  "work_items"?: ReadonlyArray<string>;
};

export type EffectiveConfig = {
  "differences"?: Record<string, string>;
  "effective": AssistantConfig;
  "requested": AssistantConfig;
  "schema_version"?: 2;
};

export type EngineerAdvice = {
  "affects_score"?: false;
  "model": (FileRef | null);
  "schema_version"?: 2;
  "status": "waiting_model" | "success" | "unavailable" | "invalid" | "timeout";
  "text": (string | null);
  "visibility"?: "public" | "hidden";
};

export type EngineerClaimedReport = {
  "config": FileRef;
  "contract_version": "engineer-review-v1";
  "created_at": string;
  "id": string;
  "pack": FileRef;
  "results": ReadonlyArray<EngineerProbeClaim>;
  "schema_version"?: 2;
};

export type EngineerFinding = {
  "description": string;
  "kind": "target_fix" | "new_regression" | "claim_consistency" | "unresolved";
  "probe_ids"?: ReadonlyArray<string>;
  "schema_version"?: 2;
  "status": "pass" | "fail" | "unverified";
  "visibility": "public" | "hidden";
};

export type EngineerProbeClaim = {
  "probe_id": string;
  "result": "pass" | "fail" | "error";
  "schema_version"?: 2;
};

export type EngineerProbeExpectation = {
  "citation_versions"?: Record<string, number>;
  "contains"?: ReadonlyArray<string>;
  "effective_update_strategy"?: ("daily" | "realtime" | "manual_policy" | null);
  "error_code"?: (string | null);
  "schema_version"?: 2;
  "status": "answered" | "answered_with_warning" | "fallback" | "failed";
};

export type EngineerProbeResult = {
  "actual": (TestResultV2 | null);
  "config_hash": string;
  "elapsed_seconds": number;
  "error_code"?: (string | null);
  "expected": EngineerProbeExpectation;
  "probe_id": string;
  "query": string;
  "result": "pass" | "fail" | "error";
  "schema_version"?: 2;
  "visibility": "public" | "hidden";
};

export type EngineerProbeSummary = {
  "errors": number;
  "failed": number;
  "passed": number;
  "schema_version"?: 2;
};

export type EngineerPublicReport = {
  "advice": (EngineerAdvice | null);
  "affects_score"?: false;
  "claim_check": "matched" | "mismatch" | "not_provided" | "unverified";
  "contract_version": "engineer-review-v1";
  "created_at": string;
  "findings": ReadonlyArray<EngineerFinding>;
  "hidden": EngineerProbeSummary;
  "id": string;
  "input_hash": string;
  "public_results": ReadonlyArray<EngineerProbeResult>;
  "reviewer": Executor;
  "schema_version"?: 2;
  "status": "verified" | "report_mismatch" | "incomplete";
  "submission": FileRef;
  "unresolved": ReadonlyArray<EngineerUnresolvedItem>;
  "work_language": "zh" | "en";
};

export type EngineerRegressionReport = {
  "advice": EngineerAdvice;
  "claim_check": "matched" | "mismatch" | "not_provided" | "unverified";
  "contract_version": "engineer-review-v1";
  "created_at": string;
  "findings": ReadonlyArray<EngineerFinding>;
  "id": string;
  "input": EngineerReviewInput;
  "input_hash": string;
  "results": ReadonlyArray<EngineerProbeResult>;
  "reviewer": Executor;
  "schema_version"?: 2;
  "status": "verified" | "report_mismatch" | "incomplete";
  "submission": FileRef;
  "unresolved": ReadonlyArray<EngineerUnresolvedItem>;
};

export type EngineerReviewInput = {
  "baseline_config": FileRef;
  "config": FileRef;
  "contract_version": "engineer-review-v1";
  "model": (FileRef | null);
  "pack": FileRef;
  "probe_ids": ReadonlyArray<string>;
  "probe_suite": FileRef;
  "resolved_config": EffectiveConfig;
  "resource_snapshot": FileRef;
  "reviewer_version": FileRef;
  "scenario": FileRef;
  "schema_version"?: 2;
  "source_as_of": VersionPoint;
  "submission": FileRef;
  "work_language": "zh" | "en";
};

export type EngineerSubmissionRecord = {
  "base_config_hash": string;
  "config": FileRef;
  "contract_version": "engineer-review-v1";
  "created_at": string;
  "executor": Executor;
  "explanation": string;
  "id": string;
  "pack": FileRef;
  "regression_report": (FileRef | null);
  "schema_version"?: 2;
  "unresolved": ReadonlyArray<EngineerUnresolvedItem>;
  "work_language": "zh" | "en";
};

export type EngineerUnresolvedItem = {
  "description": string;
  "id": string;
  "probe_ids"?: ReadonlyArray<string>;
  "schema_version"?: 2;
  "visibility"?: "public" | "hidden";
};

export type EvidenceRefV2 = {
  "config_version"?: (number | null);
  "kind": string;
  "object_id": string;
  "observed_at_seq": number;
  "quote"?: (string | null);
  "schema_version"?: 2;
  "session_id": string;
  "span_end"?: (number | null);
  "span_start"?: (number | null);
  "valid_from_seq"?: number;
  "valid_until_seq"?: (number | null);
  "version": number;
};

export type Executor = {
  "delegation_id"?: (string | null);
  "id": string;
  "kind": "human" | "external_agent" | "reference_agent" | "system";
  "schema_version"?: 2;
};

export type FileRef = {
  "media_type"?: string;
  "path": string;
  "schema_version"?: 2;
  "sha256": string;
};

export type ModelAttemptUsage = {
  "attempt_id": string;
  "cost"?: (number | null);
  "elapsed_seconds": number;
  "expected_model_revision"?: (string | null);
  "expected_provider"?: (string | null);
  "input_tokens"?: (number | null);
  "model_revision": (string | null);
  "output_tokens"?: (number | null);
  "provider": (string | null);
  "request_id": string;
  "schema_version"?: 2;
  "status": "success" | "failed" | "timeout" | "unknown";
  "usage_known": boolean;
};

export type ObjectRef = {
  "config_version"?: (number | null);
  "kind": string;
  "object_id": string;
  "schema_version"?: 2;
  "session_id": string;
  "version": number;
};

export type RetrievedChunk = {
  "id": string;
  "material_id": string;
  "ref": EvidenceRefV2;
  "schema_version"?: 2;
  "score": number;
  "version": number;
};

export type TestExecutionMetadata = {
  "attempts"?: ReadonlyArray<ModelAttemptUsage>;
  "chunks": ReadonlyArray<RetrievedChunk>;
  "cost_complete"?: boolean;
  "executed_at": string;
  "executor": Executor;
  "indexed_versions": Record<string, number>;
  "projection_actor": string;
  "schema_version"?: 2;
  "source_versions": Record<string, number>;
  "used_versions": Record<string, number>;
};

export type TestResultV2 = {
  "answer": string;
  "as_of": VersionPoint;
  "citations": ReadonlyArray<EvidenceRefV2>;
  "config": EffectiveConfig;
  "config_ref": ObjectRef;
  "declared_category"?: (string | null);
  "declared_expected"?: (string | null);
  "error_code"?: (string | null);
  "execution": TestExecutionMetadata;
  "id": string;
  "observed_coverage"?: ReadonlyArray<string>;
  "query": string;
  "schema_version"?: 2;
  "session_id": string;
  "status": "answered" | "answered_with_warning" | "fallback" | "failed";
  "version"?: number;
};

export type VersionPoint = {
  "business_seq": number;
  "schema_version"?: 2;
  "storage_revision": number;
  "workspace_revision": number;
};
